apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  generation: 1
  name: test-sample
  namespace: test-llm
spec:
  leaderWorkerTemplate:
    leaderTemplate:
      metadata: {}
      spec:
        containers:
        - image: quay.io/wewang58/llm-cpu-image:latest
          name: worker
          resources: {}
    restartPolicy: None
    size: 4
    workerTemplate:
      metadata: {}
      spec:
        containers:
        - image: quay.io/wewang58/llm-cpu-image:latest
          name: leader
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
  networkConfig:
    subdomainPolicy: Shared
  replicas: 2
  rolloutStrategy:
    rollingUpdateConfiguration:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  startupPolicy: LeaderCreated
